steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/f2p-buddy-1756234727/f2p-buddy-backend:$COMMIT_SHA', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/f2p-buddy-1756234727/f2p-buddy-backend:$COMMIT_SHA']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'f2p-buddy-api'
    - '--image'
    - 'gcr.io/f2p-buddy-1756234727/f2p-buddy-backend:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '3600'
    - '--concurrency'
    - '80'
    - '--max-instances'
    - '10'

# Store the build artifacts
images:
  - gcr.io/f2p-buddy-1756234727/f2p-buddy-backend:$COMMIT_SHA

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8